extern core.panic

%macro panic 1
  [section .rodata]
  %%panicMessage: db %1, `\n`, 0
  %ifndef _PANIC_FILE
    %%panicFile: db ' ', __FILE__, ':', 0
    %define _PANIC_FILE %%panicFile
  %endif

  __SECT__
  cli
  pushad
  pushfd
  mov eax, $
  mov ecx, __LINE__
  mov edx, _PANIC_FILE
  mov esi, %%panicMessage
  jmp core.panic
%endmacro

%macro panicc 2
  j%-1 %%panicElse
  panic %2
  %%panicElse:
%endmacro
