%macro _push 1-*
  %rep %0
    push %1
    %rotate 1
  %endrep
%endmacro

%macro _pop 1-*
  %rep %0
    %rotate -1
    pop %1
  %endrep
%endmacro

%macro _out 2 ; : : al dx
  mov dx, %1
  mov al, %2
  out dx, al
%endmacro

%macro _in 1 ; : al(byte) : dx
  mov dx, %1
  in al, dx
%endmacro

%macro _string 3+
  [section .rodata]
  %%string: db %3
  %%string.#: equ $ - %%string

  __SECT__
  mov %1, %%string.#
  mov %2, %%string
%endmacro

%macro _string 1
  _string ecx, esi, %1
%endmacro
